services:
  - type: web
    name: travel-safety-assistant
    env: node
    rootDir: aiaiproject
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production 